# Generated by Django 5.2.3 on 2025-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopownerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopownerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopownerprofile',
            name='map_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default-user.png', upload_to='profile_pics/'),
        ),
    ]
