# Generated by Django 5.1.7 on 2025-07-22 17:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='verification_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no spaces or special characters)', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='shopownerprofile',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no spaces or special characters)', regex='^\\d{10}$')]),
        ),
    ]
