# Generated by Django 5.1.7 on 2025-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pendinguser_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopownerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopownerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
