# Generated by Django 5.1.7 on 2025-08-11 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shopownerprofile_city_shopownerprofile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9 digits after +233 (e.g., +233241234567)', regex='^\\+233\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='shopownerprofile',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9 digits after +233 (e.g., +233241234567)', regex='^\\+233\\d{9}$')]),
        ),
    ]
