# Generated by Django 5.1.7 on 2025-08-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
    ]
